# Generated by Django 4.0.6 on 2022-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('energy', models.FloatField(default=0.0)),
                ('carbohydrate', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('dietary_fiber', models.FloatField(default=0.0)),
                ('magnesium', models.FloatField(default=0.0)),
                ('vitamin_c', models.FloatField(default=0.0)),
                ('vitamin_d', models.FloatField(default=0.0)),
                ('vitamin_b6', models.FloatField(default=0.0)),
                ('vitamin_b12', models.FloatField(default=0.0)),
                ('folic_acid', models.FloatField(default=0.0)),
                ('tryptophan', models.FloatField(default=0.0)),
                ('dha_epa', models.FloatField(default=0.0)),
                ('amount', models.IntegerField(default=0)),
                ('is_beverage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, to='foods.category')),
            ],
        ),
    ]
